version: "3.0"

services:

  oracle:
    image: wnameless/oracle-xe-11g:latest
    ports:
      - "1522:1521"
      - "8081:8080"
    volumes:
      - ./script/docker/oracle/create_user.sql:/docker-entrypoint-initdb.d/create_user.sql
      - ./script/docker/oracle/healthcheck.sh:/tmp/healthcheck.sh
    healthcheck:
      test: /bin/bash /tmp/healthcheck.sh
      interval: 2s
      timeout: 10s
      retries: 1800 # 2s*1800 = 3600s = 60min

  # mssqlserver:
  #   image: microsoft/mssql-server-linux:latest
  #   environment:
  #       ACCEPT_EULA: Y
  #       SA_PASSWORD: P6spyTravis
  #   ports:
  #     - "1434:1433"
  #   healthcheck:
  #     test: /bin/sh -c '/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P P6spyTravis  -Q "SELECT 12345" | grep -wq 12345'
  #     interval: 2s
  #     timeout: 10s
  #     retries: 1800 # 2s*1800 = 3600s = 60min

  # mysql:
  #   image: mysql:5.7.18
  #   environment:
  #       MYSQL_USER: travis
  #       MYSQL_PASSWORD: travis
  #       MYSQL_DATABASE: p6spy
  #       MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - ./script/docker/mysql/change_user_pwd.sql:/docker-entrypoint-initdb.d/change_user_pwd.sql
  #   healthcheck:
  #     test: /bin/sh -c "[ -d /var/lib/mysql/p6spy ]"
  #     interval: 2s
  #     timeout: 10s
  #     retries: 1800 # 2s*1800 = 3600s = 60min

  firebird:
      image: jacobalberty/firebird:2.5-sc
      environment:
        ISC_PASSWORD: masterkey
        FIREBIRD_USER: travis
        FIREBIRD_PASSWORD: travis
        FIREBIRD_DATABASE: p6spy.gdb
      ports:
        - "3050:3050"
      healthcheck:
        test: /bin/sh -c "[ -f /firebird/data/p6spy.gdb ]"
        interval: 2s
        timeout: 10s
        retries: 1800 # 2s*1800 = 3600s = 60min
